env_path: "./environments/Curriculum/envs/FetchPush_source.py"
CurriculumCfg:
  env_id: "Curriculum/FetchPush"
  num_envs: 16
  num_samples: 3
  training_alg: "SAC"
  policy_network: "MultiInputPolicy"
  eval_freq: 1_000
  short_training_timesteps: 500_000
  long_training_timesteps: 3_000_000
  evaluation_timesteps: 500

HerCfg:
  env_id: "FetchPush-v2"
  num_envs: 16
  training_alg: "SAC"
  policy_network: "MultiInputPolicy"
  eval_freq: 1_000
  training_timesteps: 10_000_000

SacCfg:
  env_id: "FetchPushDense-v2"
  num_envs: 16
  training_alg: "SAC"
  policy_network: "MultiInputPolicy"
  training_timesteps: 10_000_000
  eval_freq: 1_000

ZeroshotCfg:
  env_id: "Curriculum/FetchPush"
  num_envs: 16
  num_samples: 3
  training_alg: "SAC"
  policy_network: "MultiInputPolicy"
  eval_freq: 1_000
  training_timesteps: 10_000_000